### ISSUE TITLE
Failure to check for elasticsearch index

### ISSUE THREAD

**Issue by Pengran1** [sadsfae/ansible-elk#26] opened 2017-07-28 08:17 UTC
Hello again

 I already tried to disabled **firewalld** and **iptables** services before retrying a fresh installation, but still, this problems come up. 

“TASK [kibana : Check elasticsearch index for content] ****************************
fatal: [192.168.2.181]: FAILED! => {“changed”: false, “content”: “”, “failed”: true, “msg”: “Status code was not [200]: Request failed: “, “redirected”: false, “status”: -1, “url”: “http://localhost:9200/_cat/indices”}
to retry, use: –limit @/root/ansible-elk/install/elk.retry”

Thanks

**Comment by sadsfae** [comment] 2017-07-29 21:04
Thanks for filing this, let me see if I can reproduce this and get a fix in if so.

**Comment by sadsfae** [comment] 2017-07-29 22:09
@Pengran1 I was unable to reproduce this on a set of CentOS7 VMs (one client, one server).

(I am using 8G memory, 4vcpu for my ELK/EFK VM).

I suspect your ELK/EFK machine might be underpowered?  I have noticed that there's a performance hit in 5.x ES (and especially logstash) that I have not experienced in the 2.4 series.

I have committed a fix to wait for ES to be available before checking for content to accomodate for the service starting up.  Please give it another try.

Barring this could you try using the 2.4 branch and see if you still have a problem?

```
git clone https://github.com/sadsfae/ansible-elk
cd ansible-elk
git checkout 2.4
```

**Comment by sadsfae** [comment] 2017-08-22 19:47
Checking in here, some fixes have gone in to put in waits for ES to become available.  Can you confirm this fixes the issue you've reported please?

**Comment by sadsfae** [comment] 2017-09-06 15:34
Closing this out, please re-open after you've tried the latest fixes that have been merged if it's still an issue for you.  Thanks for filing this issue.

**Closed as completed by sadsfae** 2017-09-06 15:34 UTC
