### ISSUE TITLE
Import ElasticSearch GPG Key fails on elk client role

### ISSUE THREAD

**Issue by japplewhite** [sadsfae/ansible-elk#97] opened 2021-02-05 15:20 UTC
**Your System Details** 

**Describe the bug**
When the elk client role runs it fails on installing the GPG key for elastisearch
Making the following change fixed the issue
 #rpm_key: key=http://packages.elastic.co/GPG-KEY-elasticsearch
  rpm_key: key=https://artifacts.elastic.co/GPG-KEY-elasticsearch

**Comment by sadsfae** [comment] 2022-04-03 16:30
Thanks for filing this @japplewhite.  These seem like they same files and are both accessible, wonder if there's a benefit to one or the other.  It's been a while but I'll experiment with this and see if it's still a problem.

**Comment by sadsfae** [comment] 2023-04-29 14:12
Closing this, I'm unable to reproduce it.

**Closed as completed by sadsfae** 2023-04-29 14:12 UTC
